/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package komunat;

import java.awt.event.KeyEvent;


/**
 *
 * @author LIRIDON
 */
public class Komunat extends javax.swing.JFrame {


    public Komunat() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jNumriTabeles = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jKomunaKryesore = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Komunat = new javax.swing.JLabel();
        Komunat1 = new javax.swing.JLabel();
        Komunat2 = new javax.swing.JLabel();
        Komunat3 = new javax.swing.JLabel();
        Komunat4 = new javax.swing.JLabel();
        Komunat5 = new javax.swing.JLabel();
        Komunat6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gjths = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Numri i tabeles:");

        jNumriTabeles.setBackground(new java.awt.Color(51, 51, 51));
        jNumriTabeles.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jNumriTabeles.setForeground(java.awt.Color.white);
        jNumriTabeles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumriTabelesActionPerformed(evt);
            }
        });
        jNumriTabeles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNumriTabelesKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Komuna kryesore:");

        jKomunaKryesore.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jKomunaKryesore.setForeground(java.awt.Color.white);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Kerko");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Komunat tjera:");

        Komunat.setBackground(new java.awt.Color(51, 51, 51));
        Komunat.setForeground(java.awt.Color.white);

        Komunat1.setBackground(new java.awt.Color(51, 51, 51));
        Komunat1.setForeground(java.awt.Color.white);

        Komunat2.setBackground(new java.awt.Color(51, 51, 51));
        Komunat2.setForeground(java.awt.Color.white);

        Komunat3.setBackground(new java.awt.Color(51, 51, 51));
        Komunat3.setForeground(java.awt.Color.white);

        Komunat4.setBackground(new java.awt.Color(51, 51, 51));
        Komunat4.setForeground(java.awt.Color.white);

        Komunat5.setBackground(new java.awt.Color(51, 51, 51));
        Komunat5.setForeground(java.awt.Color.white);

        Komunat6.setBackground(new java.awt.Color(51, 51, 51));
        Komunat6.setForeground(java.awt.Color.white);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Gjithsej:");

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("38 komuna");

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Gjithesej:");

        gjths.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        gjths.setForeground(java.awt.Color.white);

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("komuna ketu");

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Komunat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jNumriTabeles, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(gjths, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jKomunaKryesore, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Komunat6, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Komunat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Komunat1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Komunat2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Komunat3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Komunat4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Komunat5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jNumriTabeles, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gjths, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jKomunaKryesore, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Komunat, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Komunat1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Komunat2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Komunat3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Komunat4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Komunat5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Komunat6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5)
                    .addComponent(jButton2))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jNumriTabelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumriTabelesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jNumriTabelesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jNumriTabeles.getText().equals("01")){
            jKomunaKryesore.setText("Prishtina");
            Komunat.setText("Drenas");
            Komunat1.setText("Graçanica");
            Komunat2.setText("Fushe Kosova");
            Komunat3.setText("Lipjani");
            Komunat4.setText("Artana");
            Komunat5.setText("Podujeva");
            Komunat6.setText("Besiana");
            gjths.setText("8");
        }else if(jNumriTabeles.getText().equals("02")){
             jKomunaKryesore.setText("Mitrovica");
             Komunat.setText("Albaniku");
             Komunat1.setText("Mitrovica Veriore");
             Komunat2.setText("Skenderaji");
             Komunat3.setText("Vushtrria");
             Komunat4.setText("Zubin Potoku");
             Komunat5.setText("Zveçani");
             Komunat6.setText("");
             gjths.setText("7");
        }else if(jNumriTabeles.getText().equals("03")){
            jKomunaKryesore.setText("Peja");
            Komunat.setText("Burimi");
            Komunat1.setText("Klina");
            Komunat2.setText("");
            Komunat3.setText("");
            Komunat4.setText("");
            Komunat5.setText("");
            Komunat6.setText("");
            gjths.setText("3");
        }else if(jNumriTabeles.getText().equals("04")){
            jKomunaKryesore.setText("Prizreni");
            Komunat.setText("Sharri");
            Komunat1.setText("Malisheva");
            Komunat2.setText("Mamusha");
            Komunat3.setText("Theranda");
            Komunat4.setText("");
            Komunat5.setText("");
            Komunat6.setText("");
            gjths.setText("5");
        }else if(jNumriTabeles.getText().equals("05")){
            jKomunaKryesore.setText("Ferizaji");
            Komunat.setText("Hani i Elezit");
            Komunat1.setText("Kaçaniku");
            Komunat2.setText("Shtime");
            Komunat3.setText("Shterpce");
            Komunat4.setText("");
            Komunat5.setText("");
            Komunat6.setText("");
            gjths.setText("5");
        }else if(jNumriTabeles.getText().equals("06")){
            jKomunaKryesore.setText("Gjilani");
            Komunat.setText("Dardana");
            Komunat1.setText("Kllokoti");
            Komunat2.setText("Parteshi");
            Komunat3.setText("Ranillugu");
            Komunat4.setText("Vitia");
            Komunat5.setText("");
            Komunat6.setText("");
            gjths.setText("6");
        }else if(jNumriTabeles.getText().equals("07")){
            jKomunaKryesore.setText("Gjakova");
            Komunat.setText("Rahoveci");
            Komunat1.setText("Juniku");
            Komunat2.setText("Deçani");
            Komunat3.setText("");
            Komunat4.setText("");
            Komunat5.setText("");
            Komunat6.setText("");
            gjths.setText("4");
        }else{
            if(jNumriTabeles.getText().trim().isEmpty()){
                jKomunaKryesore.setText("");
                Komunat.setText("");
                Komunat1.setText("");
                Komunat2.setText("");
                Komunat3.setText("");
                Komunat4.setText("");
                Komunat5.setText("");
                Komunat6.setText("");
                gjths.setText("");
            }else{
                jKomunaKryesore.setText("ERROR");
                Komunat.setText("ERROR");
                Komunat1.setText("");
                Komunat2.setText("");
                Komunat3.setText("");
                Komunat4.setText("");
                Komunat5.setText("");
                Komunat6.setText("");
                gjths.setText("0");
            }
        }
        // 38 komuna
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jNumriTabelesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNumriTabelesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        if(jNumriTabeles.getText().equals("01")){
            jKomunaKryesore.setText("Prishtina");
            Komunat.setText("Dresa");
            Komunat1.setText("Graçanica");
            Komunat2.setText("Fushe Kosova");
            Komunat3.setText("Lipjani");
            Komunat4.setText("Artana");
            Komunat5.setText("Kastrioti");
            Komunat6.setText("Besiana");
            gjths.setText("8");
        }else if(jNumriTabeles.getText().equals("02")){
             jKomunaKryesore.setText("Mitrovica");
             Komunat.setText("Albaniku");
             Komunat1.setText("Mitrovica Veriore");
             Komunat2.setText("Skenderaji");
             Komunat3.setText("Vushtrria");
             Komunat4.setText("Zubin Potoku");
             Komunat5.setText("Zveçani");
             Komunat6.setText("");
             gjths.setText("7");
        }else if(jNumriTabeles.getText().equals("03")){
            jKomunaKryesore.setText("Peja");
            Komunat.setText("Burimi");
            Komunat1.setText("Klina");
            Komunat2.setText("");
            Komunat3.setText("");
            Komunat4.setText("");
            Komunat5.setText("");
            Komunat6.setText("");
            gjths.setText("3");
        }else if(jNumriTabeles.getText().equals("04")){
            jKomunaKryesore.setText("Prizreni");
            Komunat.setText("Sharri");
            Komunat1.setText("Malisheva");
            Komunat2.setText("Mamusha");
            Komunat3.setText("Theranda");
            Komunat4.setText("");
            Komunat5.setText("");
            Komunat6.setText("");
            gjths.setText("5");
        }else if(jNumriTabeles.getText().equals("05")){
            jKomunaKryesore.setText("Ferizaji");
            Komunat.setText("Hani i Elezit");
            Komunat1.setText("Kaçaniku");
            Komunat2.setText("Shtime");
            Komunat3.setText("Shterpce");
            Komunat4.setText("");
            Komunat5.setText("");
            Komunat6.setText("");
            gjths.setText("5");
        }else if(jNumriTabeles.getText().equals("06")){
            jKomunaKryesore.setText("Gjilani");
            Komunat.setText("Dardana");
            Komunat1.setText("Kllokoti");
            Komunat2.setText("Parteshi");
            Komunat3.setText("Ranillugu");
            Komunat4.setText("Vitia");
            Komunat5.setText("");
            Komunat6.setText("");
            gjths.setText("6");
        }else if(jNumriTabeles.getText().equals("07")){
            jKomunaKryesore.setText("Gjakova");
            Komunat.setText("Rahoveci");
            Komunat1.setText("Juniku");
            Komunat2.setText("Deçani");
            Komunat3.setText("");
            Komunat4.setText("");
            Komunat5.setText("");
            Komunat6.setText("");
            gjths.setText("4");
        }else{
            if(jNumriTabeles.getText().trim().isEmpty()){
                jKomunaKryesore.setText("");
                Komunat.setText("");
                Komunat1.setText("");
                Komunat2.setText("");
                Komunat3.setText("");
                Komunat4.setText("");
                Komunat5.setText("");
                Komunat6.setText("");
                gjths.setText("");
            }else{
                jKomunaKryesore.setText("ERROR");
                Komunat.setText("ERROR");
                Komunat1.setText("");
                Komunat2.setText("");
                Komunat3.setText("");
                Komunat4.setText("");
                Komunat5.setText("");
                Komunat6.setText("");
                gjths.setText("0");
            }
        }
        }
    }//GEN-LAST:event_jNumriTabelesKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Targat().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Komunat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Komunat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Komunat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Komunat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Komunat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Komunat;
    private javax.swing.JLabel Komunat1;
    private javax.swing.JLabel Komunat2;
    private javax.swing.JLabel Komunat3;
    private javax.swing.JLabel Komunat4;
    private javax.swing.JLabel Komunat5;
    private javax.swing.JLabel Komunat6;
    private javax.swing.JLabel gjths;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jKomunaKryesore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jNumriTabeles;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
