/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package komunat;

import java.awt.event.KeyEvent;

/**
 *
 * @author LIRIDON
 */
public class Targat extends javax.swing.JFrame {

    /**
     * Creates new form Targat
     */
    public Targat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        komuna = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        targa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Komuna:");

        komuna.setBackground(new java.awt.Color(51, 51, 51));
        komuna.setForeground(java.awt.Color.white);
        komuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                komunaActionPerformed(evt);
            }
        });
        komuna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                komunaKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Targa:");

        targa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        targa.setForeground(java.awt.Color.white);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setText("Kerko");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        error.setForeground(java.awt.Color.red);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(java.awt.Color.white);
        jButton2.setText("Fshi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(51, 51, 51));
        back.setForeground(java.awt.Color.white);
        back.setText("<");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(komuna, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(targa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(back)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(back)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(komuna, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(targa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // deklarimi i komunes
        String komunat = komuna.getText();
        
        // kerkimi per komunen
        switch(komunat.toLowerCase()){ //e kthejn ne shkronja te vogla
            
            case "prishtin":
            case "prishtina":
            case "prishtine":
                targa.setText("01");
                error.setText("");
                break;
            
            case "drenasi":
            case "drenas":
            case "drenic":
            case "drenasë":
                targa.setText("01");
                error.setText("");
                break;
                
            case "gracanica":
            case "graqanica":
            case "gracanic":
            case "graqanic":
            case "graçanica":
            case "graçanic":
                targa.setText("01");
                error.setText("");
                break;
                
            case "fush kosov":
            case "fushe kosov":
            case "fush kosove":
            case "fushe kosove":
            case "fushë kosov":
            case "fush kosovë":
            case "fushë kosovë":
                targa.setText("01");
                error.setText("");
                break;
                
            case "lipjan":
            case "lipjani":
            case "lipjane":
            case "lipjanë":
                targa.setText("01");
                error.setText("");
                break;
                
            case "podujev":
            case "podujeva":
            case "podujeve":
            case "podujevë":
                targa.setText("01");
                error.setText("");
                break;
                
            case "artana":
            case "artan":
            case "artanë":
                targa.setText("01");
                error.setText("");
                break;
                
            case "kastrioti":
            case "kastriot":
            case "kastriote":
            case "kastriotë":
                targa.setText("01");
                error.setText("");
                break;
            
            case "besiana":
            case "besian":
            case "besiane":
            case "besianë":
                targa.setText("01");
                error.setText("");
                break;
                
            case "mitrovic":
            case "mitrovicë":
            case "mitrovice":
            case "mitrovica":
                targa.setText("02");
                error.setText("");
                break;
                
            case "albaniku":
            case "albanik":
            case "albanike":
            case "albanikë":
                targa.setText("02");
                error.setText("");
                break;
                
            case "mitrovica veriore":
            case "mitrovica verior":
            case "mitrovica veriorë":
            case "mitrovic veriore":
            case "mitrovic verior":
            case "mitrovic veriorë":
            case "mitrovice veriore":
            case "mitrovice verior":
            case "mitrovice veriorë":
            case "mitrovicë veriore":
            case "mitrovicë verior":
            case "mitrovicë veriorë":
                targa.setText("02");
                error.setText("");
                break;
                
            case "skenderaj":
            case "skenderaji":
            case "skenderajë":
            case "skenderaje":
                targa.setText("02");
                error.setText("");
                break;
                
            case "vushtrria":
            case "vushtrri":
            case "vushtria":
            case "vushtri":
                targa.setText("02");
                error.setText("");
                break;
                
            case "zubin potoku":
            case "zubin potok":
            case "zubin potoke":
            case "zubin potokë":
                targa.setText("02");
                error.setText("");
                break;
                
            case "zvaqan":
            case "zvaqane":
            case "zvaqanë":
            case "zvaqani":
                
            case "zvaçan":
            case "zvaçane":
            case "zvaçanë":
            case "zvaçani":
                targa.setText("02");
                error.setText("");
                break;
                
            case "peja":
            case "pej":
            case "peje":
            case "pejë":
                targa.setText("03");
                error.setText("");
                break;
                
            case "burimi":
            case "burim":
            case "burime":
            case "burimë":
                targa.setText("03");
                error.setText("");
                break;
                
            case "klina":
            case "kline":
            case "klinë":
            case "klin":
                targa.setText("03");
                error.setText("");
                break;
                
            case "prizren":
            case "prizreni":
            case "prizrene":
            case "prizrenë":
                targa.setText("04");
                error.setText("");
                break;
                
            case "sharri":
            case "sharre":
            case "share":
            case "shar":
            case "sharr":
            case "shari":
            case "sharrë":
            case "sharë":
                targa.setText("04");
                error.setText("");
                break;
                
            case "malishev":
            case "malisheve":
            case "malisheva":
            case "malishevë":
                targa.setText("04");
                error.setText("");
                break;
                
            case "mamusha":
            case "mamushe":
            case "mamush":
            case "mamushë":
                targa.setText("04");
                error.setText("");
                break;
                
            case "theranda":
            case "therand":
            case "therande":
            case "therandë":
                targa.setText("04");
                error.setText("");
                break;
                
            case "ferizaj":
            case "ferizaje":
            case "ferizajë":
                targa.setText("05");
                error.setText("");
                break;
                
            case "hani i elezit":
            case "hani i elezi":
            case "hani i elezite":
            case "hani i elezitë":
                
            case "han i elezit":
            case "han i elezi":
            case "han i elezite":
            case "han i elezitë":
                
            case "hani elezit":
            case "hani elezi":
            case "hani elezite":
            case "hani elezitë":
                
            case "han elezit":
            case "han elezi":
            case "han elezite":
            case "han elezitë":
                targa.setText("05");
                error.setText("");
                break;
                
            case "kaqanik":
            case "kaqanike":
            case "kaqanikë":
            case "kaqaniku":
            case "kaqaniki":
                
            case "kaçanik":
            case "kaçanike":
            case "kaçanikë":
            case "kaçaniku":
            case "kaçaniki":
                targa.setText("05");
                error.setText("");
                break;
                
            case "shtime":
            case "shtim":
            case "shtimë":
            case "shtima":
                
            case "shtimje":
            case "shtimja":
                targa.setText("05");
                error.setText("");
                break;
                
            case "shterpc":
            case "shterpce":
            case "shterpcë":
            case "shterpca":
            case "shterpci":
                
            case "shtërpc":
            case "shtërpce":
            case "shtërpcë":
            case "shtërpca":
            case "shtërpci":
                targa.setText("05");
                error.setText("");
                break;
                
            case "gjilan":
            case "gjilanë":
            case "gjilane":
            case "gjilani":
                
            case "gilan":
            case "gilanë":
            case "gilane":
            case "gilani":
                targa.setText("06");
                error.setText("");
                break;
                
            case "dardan":
            case "dardani":
            case "dardana":
            case "dardane":
            case "dardanë":
                targa.setText("06");
                error.setText("");
                break;
                
            case "kllokot":
            case "kllokoti":
            case "kllokote":
            case "kllokotë":
                targa.setText("06");
                error.setText("");
                break;
                
            case "partesh":
            case "parteshi":
            case "parteshe":
            case "parteshë":
            case "partesha":
                targa.setText("06");
                error.setText("");
                break;
                
            case "ranillug":
            case "ranillugu":
            case "ranillugi":
            case "ranilluga":
                targa.setText("06");
                error.setText("");
                break;
                
            case "viti":
            case "vitia":
                targa.setText("06");
                error.setText("");
                break;
                
            case "gjakov":
            case "gjakove":
            case "gjakovë":
            case "gjakova":
                targa.setText("07");
                error.setText("");
                break;
                
            case "junik":
            case "juniku":
            case "junike":
            case "junikë":
                targa.setText("07");
                error.setText("");
                break;
                
            case "rahovec":
            case "rahoveci":
            case "rahovece":
            case "rahovecë":
                targa.setText("07");
                error.setText("");
                break;
                
            case "deqan":
            case "deqani":
            case "deqane":
            case "deqanë":
                
            case "deçan":
            case "deçani":
            case "deçane":
            case "deçanë":
                targa.setText("07");
                error.setText("");
                break;
            
            default:
                error.setText("Gabim komuna !");
                targa.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        komuna.setText("");
        targa.setText("");
        error.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void komunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_komunaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_komunaActionPerformed

    private void komunaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_komunaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            // deklarimi i komunes
        String komunat = komuna.getText();
        
        // kerkimi per komunen
        switch(komunat.toLowerCase()){ //e kthejn ne shkronja te vogla
            
            case "prishtin":
            case "prishtina":
            case "prishtine":
                targa.setText("01");
                error.setText("");
                break;
            
            case "drenasi":
            case "drenas":
            case "drenic":
            case "drenasë":
                targa.setText("01");
                error.setText("");
                break;
                
            case "gracanica":
            case "graqanica":
            case "gracanic":
            case "graqanic":
            case "graçanica":
            case "graçanic":
                targa.setText("01");
                error.setText("");
                break;
                
            case "fush kosov":
            case "fushe kosov":
            case "fush kosove":
            case "fushe kosove":
            case "fushë kosov":
            case "fush kosovë":
            case "fushë kosovë":
                targa.setText("01");
                error.setText("");
                break;
                
            case "podujev":
            case "podujeva":
            case "podujeve":
            case "podujevë":
                targa.setText("01");
                error.setText("");
                break;
                
            case "lipjan":
            case "lipjani":
            case "lipjane":
            case "lipjanë":
                targa.setText("01");
                error.setText("");
                break;
                
            case "artana":
            case "artan":
            case "artanë":
                targa.setText("01");
                error.setText("");
                break;
                
            case "kastrioti":
            case "kastriot":
            case "kastriote":
            case "kastriotë":
                targa.setText("01");
                error.setText("");
                break;
            
            case "besiana":
            case "besian":
            case "besiane":
            case "besianë":
                targa.setText("01");
                error.setText("");
                break;
                
            case "mitrovic":
            case "mitrovicë":
            case "mitrovice":
            case "mitrovica":
                targa.setText("02");
                error.setText("");
                break;
                
            case "albaniku":
            case "albanik":
            case "albanike":
            case "albanikë":
                targa.setText("02");
                error.setText("");
                break;
                
            case "mitrovica veriore":
            case "mitrovica verior":
            case "mitrovica veriorë":
            case "mitrovic veriore":
            case "mitrovic verior":
            case "mitrovic veriorë":
            case "mitrovice veriore":
            case "mitrovice verior":
            case "mitrovice veriorë":
            case "mitrovicë veriore":
            case "mitrovicë verior":
            case "mitrovicë veriorë":
                targa.setText("02");
                error.setText("");
                break;
                
            case "skenderaj":
            case "skenderaji":
            case "skenderajë":
            case "skenderaje":
                targa.setText("02");
                error.setText("");
                break;
                
            case "vushtrria":
            case "vushtrri":
            case "vushtria":
            case "vushtri":
                targa.setText("02");
                error.setText("");
                break;
                
            case "zubin potoku":
            case "zubin potok":
            case "zubin potoke":
            case "zubin potokë":
                targa.setText("02");
                error.setText("");
                break;
                
            case "zvaqan":
            case "zvaqane":
            case "zvaqanë":
            case "zvaqani":
                
            case "zvaçan":
            case "zvaçane":
            case "zvaçanë":
            case "zvaçani":
                targa.setText("02");
                error.setText("");
                break;
                
            case "peja":
            case "pej":
            case "peje":
            case "pejë":
                targa.setText("03");
                error.setText("");
                break;
                
            case "burimi":
            case "burim":
            case "burime":
            case "burimë":
                targa.setText("03");
                error.setText("");
                break;
                
            case "klina":
            case "kline":
            case "klinë":
            case "klin":
                targa.setText("03");
                error.setText("");
                break;
                
            case "prizren":
            case "prizreni":
            case "prizrene":
            case "prizrenë":
                targa.setText("04");
                error.setText("");
                break;
                
            case "sharri":
            case "sharre":
            case "share":
            case "shar":
            case "sharr":
            case "shari":
            case "sharrë":
            case "sharë":
                targa.setText("04");
                error.setText("");
                break;
                
            case "malishev":
            case "malisheve":
            case "malisheva":
            case "malishevë":
                targa.setText("04");
                error.setText("");
                break;
                
            case "mamusha":
            case "mamushe":
            case "mamush":
            case "mamushë":
                targa.setText("04");
                error.setText("");
                break;
                
            case "theranda":
            case "therand":
            case "therande":
            case "therandë":
                targa.setText("04");
                error.setText("");
                break;
                
            case "ferizaj":
            case "ferizaje":
            case "ferizajë":
                targa.setText("05");
                error.setText("");
                break;
                
            case "hani i elezit":
            case "hani i elezi":
            case "hani i elezite":
            case "hani i elezitë":
                
            case "han i elezit":
            case "han i elezi":
            case "han i elezite":
            case "han i elezitë":
                
            case "hani elezit":
            case "hani elezi":
            case "hani elezite":
            case "hani elezitë":
                
            case "han elezit":
            case "han elezi":
            case "han elezite":
            case "han elezitë":
                targa.setText("05");
                error.setText("");
                break;
                
            case "kaqanik":
            case "kaqanike":
            case "kaqanikë":
            case "kaqaniku":
            case "kaqaniki":
                
            case "kaçanik":
            case "kaçanike":
            case "kaçanikë":
            case "kaçaniku":
            case "kaçaniki":
                targa.setText("05");
                error.setText("");
                break;
                
            case "shtime":
            case "shtim":
            case "shtimë":
            case "shtima":
                
            case "shtimje":
            case "shtimja":
                targa.setText("05");
                error.setText("");
                break;
                
            case "shterpc":
            case "shterpce":
            case "shterpcë":
            case "shterpca":
            case "shterpci":
                
            case "shtërpc":
            case "shtërpce":
            case "shtërpcë":
            case "shtërpca":
            case "shtërpci":
                targa.setText("05");
                error.setText("");
                break;
                
            case "gjilan":
            case "gjilanë":
            case "gjilane":
            case "gjilani":
                
            case "gilan":
            case "gilanë":
            case "gilane":
            case "gilani":
                targa.setText("06");
                error.setText("");
                break;
                
            case "dardan":
            case "dardani":
            case "dardana":
            case "dardane":
            case "dardanë":
                targa.setText("06");
                error.setText("");
                break;
                
            case "kllokot":
            case "kllokoti":
            case "kllokote":
            case "kllokotë":
                targa.setText("06");
                error.setText("");
                break;
                
            case "partesh":
            case "parteshi":
            case "parteshe":
            case "parteshë":
            case "partesha":
                targa.setText("06");
                error.setText("");
                break;
                
            case "ranillug":
            case "ranillugu":
            case "ranillugi":
            case "ranilluga":
                targa.setText("06");
                error.setText("");
                break;
                
            case "viti":
            case "vitia":
                targa.setText("06");
                error.setText("");
                break;
                
            case "gjakov":
            case "gjakove":
            case "gjakovë":
            case "gjakova":
                targa.setText("07");
                error.setText("");
                break;
                
            case "junik":
            case "juniku":
            case "junike":
            case "junikë":
                targa.setText("07");
                error.setText("");
                break;
                
            case "rahovec":
            case "rahoveci":
            case "rahovece":
            case "rahovecë":
                targa.setText("07");
                error.setText("");
                break;
                
            case "deqan":
            case "deqani":
            case "deqane":
            case "deqanë":
                
            case "deçan":
            case "deçani":
            case "deçane":
            case "deçanë":
                targa.setText("07");
                error.setText("");
                break;
            
            default:
                error.setText("Gabim komuna !");
                targa.setText("");
        }
        }
    }//GEN-LAST:event_komunaKeyPressed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new Komunat().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Targat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Targat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Targat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Targat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Targat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField komuna;
    private javax.swing.JLabel targa;
    // End of variables declaration//GEN-END:variables
}
